version: 2.1

orbs:
  ci-caching: jobcloud/ci-caching@3.2
  ci-php: jobcloud/ci-php@2.12

workflows:
  version: 2
  test-avro-validator:
    jobs:
      - ci-caching/build-docker-images:
          context: dockerhub-credentials
      - ci-php/install-dependencies:
          context: dockerhub-credentials
          sshFingerprint: "26:9f:79:7a:8d:bc:c7:42:07:ba:04:f1:99:f3:36:61"
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-caching/build-docker-images
      - ci-php/coverage:
          context: dockerhub-credentials
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
      - ci-php/code-style:
          context: dockerhub-credentials
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
      - ci-php/static-analysis:
          context: dockerhub-credentials
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
      - ci-php/infection-testing:
          context: dockerhub-credentials
          dependencyCheckSumFile: "./composer.json"
          requires:
            - ci-php/install-dependencies
      - ci-php/todo-checker:
          name: todo-check
          context:
            - todochecker
  daily:
    triggers:
      - schedule:
          cron: "0 7 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - ci-caching/build-docker-images:
          context: dockerhub-credentials
          name: build-docker-images
      - ci-php/install-dependencies:
          context: dockerhub-credentials
          name: install-dependencies
          dependencyCheckSumFile: "./composer.json"
          requires:
            - build-docker-images
      - ci-php/composer-audit:
          context: dockerhub-credentials
          dependencyCheckSumFile: "./composer.json"
          requires:
            - build-docker-images
            - install-dependencies
  monthly:
    triggers:
      - schedule:
          cron: "0 8 1 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - ci-caching/build-docker-images:
          context: dockerhub-credentials
          name: build-docker-images
      - ci-caching/build-docker-image:
          context: dockerhub-credentials
          name: build-composer-outdated-dependencies
          dockerFolder: "./docker/dev/php"
          requires:
            - build-docker-images
      - ci-php/install-dependencies-with-docker:
          context: dockerhub-credentials
          name: install-dependencies
          sshFingerprint: "26:9f:79:7a:8d:bc:c7:42:07:ba:04:f1:99:f3:36:61"
          dependencyCheckSumFile: "./composer.json"
          requires:
            - build-composer-outdated-dependencies
      - composer-outdated-dependencies:
          context: dockerhub-credentials
          requires:
            - install-dependencies
jobs:
  composer-outdated-dependencies:
    machine: true
    steps:
      - ci-php/add-ssh-key-command:
          sshFingerprint: "26:9f:79:7a:8d:bc:c7:42:07:ba:04:f1:99:f3:36:61"
      - ci-caching/run-docker-from-restored-caches:
          dependencyCheckSumFile: './composer.json'
      - ci-caching/execute-in-container:
          info: "composer outdated packages"
          container: php
          command: "composer-outdated"
