version: '3.2'
services:
  php:
    build:
      context: ./
      dockerfile: dev/php/Dockerfile
      args:
        HOST_USER_ID: ${USER_ID}
    container_name: avro-validator
    hostname: avro-validator
    tty: true
    volumes:
      - ../:/var/www/html
